scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]
  - job_name: "ec2_nodes"
    static_configs:
      - targets: ["172.31.23.163:9100"]

        crape_configs:
          - job_name: "prometheus"
            static_configs:
              - targets: [ "localhost:9090" ]
          - job_name: "ec2_nodes"
            ec2-sd_configs:
              - region: us-east-1
                port: 9100